### ISSUE TITLE
Serve site via HTTPS

### ISSUE THREAD

**Issue by benbalter** [aaronjorbin/scotchisforshippers.com#1]
While the GitHub Pages team was discussing [our recent :ship: to support HTTPS for custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/),  http://scotchisforshippers.com/ came up. Ironically, we noticed we couldn't use it, because well, it wasn't served over HTTPS. 

It looks like the site is just a static site served from Linode. While it'd be awesome if you were willing to take the time to go the Let's Encrypt or a similar route to secure a cert there, we'd be glad to help you move the site over to GitHub Pages (so that we can all celebrate together).

Practically, it'd just be a matter of adding a custom domain via the repo's settings, [updating the DNS](https://help.github.com/articles/setting-up-an-apex-domain/), and once the certificate is issued, opting in to enforce HTTPS (redirect from HTTP to HTTPS).

Thanks for providing a great service and hoping we can return the favor. :smile: 🥂

**Comment by aaronjorbin** [comment]
I'd love to do this, but according to the github UI, I can't ☹️ 

<img width="694" alt="screen shot 2018-05-17 at 5 44 42 pm" src="https://user-images.githubusercontent.com/622599/40205459-1870e9f4-59fa-11e8-88aa-a78975df938f.png">

**Comment by aaronjorbin** [comment]
🚢 === 🥃

**Comment by benbalter** [comment]
Thank you, sir! 🎩
